# Generated by Django 4.2.5 on 2024-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='inst_num',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='swift_code',
            field=models.IntegerField(max_length=100),
        ),
    ]
