# Generated by Django 4.2.5 on 2024-01-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bankmodel_inst_num_alter_bankmodel_swift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='inst_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='swift_code',
            field=models.IntegerField(),
        ),
    ]
